version: '3.9'
services:
  matcher-service:
    build: ./matcher-service
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
      - mongo

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
