spring:
  application:
    name: matcher-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

ai:
  service:
    base-url: http://localhost:8000
